export const types = {
    SET_LOADING : 'SET_LOADING',
    SET_MODAL_STATUS: 'SET_MODAL_STATUS',
    GET_NOTES: 'GET_NOTES',
    SET_NOTE_EDIT: 'SET_NOTE_EDIT',
    SAVE_EDIT: 'SAVE_EDIT',
    SAVE_NEW: 'SAVE_NEW',
    DELETE_EVENT: 'DELETE_EVENT',
    SET_NEW_ITEM: 'SET_NEW_ITEM',

}