export const types = {
    SET_LOADING : 'SET_LOADING',
    SET_MODAL_STATUS: 'SET_MODAL_STATUS',
    GET_NOTES: 'GET_NOTES',
    SET_NOTE_EDIT: 'SET_NOTE_EDIT',
    SAVE_EDIT: 'SAVE_EDIT',
    SAVE_NEW: 'SAVE_NEW',
    DELETE_EVENT: 'DELETE_EVENT',
    SET_NEW_ITEM: 'SET_NEW_ITEM',
    AUTH_CHECKING: 'AUTH_CHECKING',
    AUTH_CHECKING_FINISH: 'AUTH_CHECKING_FINISH',
    AUTH_START_LOGIN: 'AUTH_START_LOGIN',
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_START_REGISTER: 'AUTH_START_REGISTER',
    AUTH_START_TOKEN_RENEW: 'AUTH_START_TOKEN_RENEW',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    SET_LOGIN_USER: 'SET_LOGIN_USER',
    SET_ERROR: 'SET_ERROR'
}
